import type { Locale } from "./strategies";

const zh = {
  diagramChecks: "43 项验收", diagramRetention: "保留期限", diagramOld: "7 天", diagramNew: "48 小时", diagramDecision: "保留最终决定",
  title: "上下文策略图谱", lab: "策略实验室", compare: "机制对照", cases: "案例与实测", github: "查看源码", language: "Switch to English", skip: "跳到主要内容",
  collection: "策略索引", count: "9 套实现", native: "原生", adapters: "DSH 适配插件", edition: "研究笔记 / 01", sidebarNote: "同一个问题，九种取舍。", sidebarDetail: "理解编码 Agent 如何记住任务、整理历史，并继续工作。",
  eyebrow: "CONTEXT ENGINEERING", heading: "上下文的每一次取舍。", intro: "跟随一段对话，看信息如何被清理、压缩、保留与恢复。",
  viewSource: "实现说明", mechanism: "机制演示", simulation: "示意数据 · 不调用模型", window: "模型窗口", scenario: "对话场景", scenarios: ["长任务协作", "工具输出膨胀", "反复调整需求"],
  contextFlow: "上下文流转", flowHint: "选择步骤，查看每一次变化", before: "原始上下文", after: "下一次请求", original: "完整事件日志", originalHint: "追加记录 · 可回放", protected: "指令", conversation: "对话", tools: "工具结果", recent: "近期消息", summary: "摘要", restored: "恢复内容", free: "可用空间",
  play: "播放演示", pause: "暂停", replay: "重新播放", previous: "上一步", next: "下一步", reset: "重置", speed: "播放速度", stage: "步骤", waiting: "等待生成", retained: "原文保留", condensed: "收拢为摘要", pruned: "精简工具文本", processing: "整理历史", committed: "检查点已提交",
  tokensBefore: "压缩前", tokensAfter: "投影后", reduction: "示意缩减", traceCaption: "演示固定走完一次有效的压缩路径，文本块与 token 数为教学样例。实际选择、摘要长度和恢复量取决于会话及配置。",
  guard: "原始日志保留", pairs: "工具调用成对", configured: "路径说明", trigger: "默认触发预算", threshold: "触发线", retention: "保留策略", recovery: "恢复方式", formulaNote: "O = 8,192；未提供独立输入上限。触发预算来自实现默认值，流转图为示意。",
  principle: "设计取舍", behavior: "流程解读", sourceNote: "来源与适配边界", explore: "切换左侧策略，观察不同的保留方式。", sourceDate: "资料快照 · 2026.10", footer: "为理解上下文而做。", project: "dsh-context-zoo / Context Atlas", allStrategies: "全部策略",
  compareEyebrow: "SIDE BY SIDE", compareHeading: "同一段历史，不同的保留方式。", compareIntro: "比较默认预算与恢复路径。具体机制以固定版本和 DSH 适配说明为准。", strategy: "实现", pruning: "工具剪枝", defaultOn: "默认开启", optional: "可选", noPrune: "无独立阶段", compareNote: "原生 Harness 与 zoo 插件来自不同版本。触发公式使用相同的 W、O 假设；保留预算的语义不同，不适合直接排序。",
  casesEyebrow: "FROM THE WORKBENCH", casesHeading: "从机制，走进具体任务。", casesIntro: "可复核的模型实测，以及常见工程场景中的上下文取舍。", measured: "仓库实测", illustrative: "生产场景示例", caseOne: "一张发票，十个开发阶段。", caseOneDesc: "真实模型完成发票导入任务，在阶段 3、6、9 后检查压缩与磁盘重载，最后继续实现批处理取消。", caseTwo: "当测试日志占满了窗口。", caseTwoDesc: "CI 排障中，重复堆栈和大量工具输出淹没关键信息。先清理哪些内容，比立即摘要更重要。", caseThree: "长任务里，需求改了三次。", caseThreeDesc: "从初始方案到最终约束，如何在压缩之后保留用户真正的决定，避免把已撤销的要求带回来。", openCase: "展开案例", closeCase: "收起案例", exploreStrategy: "在实验室查看", evidence: "查看原始报告", context: "任务背景", decision: "策略如何介入", outcome: "观察与边界",
  caseOneContext: "invoice-import-v2：幂等导入、重试、租户隔离与批处理取消。每次运行使用新的项目和会话，最终执行 43 项验收。", caseOneDecision: "八个插件分别运行固定预算与默认参数，共享一个未压缩基线，共 17 次任务运行。在三处边界执行手动压缩，再从磁盘恢复后继续编码。", caseOneOutcome: "默认参数 8/8 通过任务验收，但只有 5/8 满足三个成功摘要等完整协议。每种模式仅运行一次，不能推断策略优劣。原生 Harness 不在本轮评测中。",
  caseTwoContext: "示例：单体仓库的测试失败产生大量重复日志。目标是保留失败断言、相关文件和最近一次命令，而非让所有历史输出持续占据窗口。", caseTwoDecision: "挂载剪枝器的 Harness 可以在摘要前缩短工具结果，重新计量。若压力已经解除，可以不调用摘要模型。Qwen、ZCode 有不同的微压缩触发与保护规则。", caseTwoOutcome: "这是依据源码机制构造的工程场景，未宣称客户生产数据或节省比例。错误结果、近期输出和配对边界的保护条件需按具体实现核对。",
  caseThreeContext: "示例：数据迁移方案从保留 7 天改为 48 小时，并补充租户隔离和禁止自动执行生产迁移的约束。长会话中，早期要求不能覆盖最终决定。", caseThreeDecision: "Codex 保留近期用户文本；Kimi 在完整摘要后恢复原始用户输入；Claude Code、Qwen 和 ZCode 还会恢复可用计划与文件状态。", caseThreeOutcome: "检查最终约束、待办与已经撤销的方案是否被区分。仓库的单次召回测试使用合成事实，不能代替真实业务数据上的验证。",
  resultsTitle: "真实模型，原始观察。", resultsIntro: "deepseek-flash · 合成任务 · 2026-09-26 / 27 / 29", recall: "单次压缩与召回", continuation: "十阶段编码续接", beforeTokens: "压缩前估算", afterTokens: "压缩后估算", decrease: "缩减", recallScore: "事实召回", summaryCap: "摘要上限", fixed: "固定预算", defaults: "默认参数", checks: "代码验收", compactions: "成功摘要", incomplete: "未完成", notRank: "单次观察，不是排行榜。", resultNote: "单次召回基于同一份 5,506-token 合成历史；Qwen 摘要上限 4,096，其余为 2,048。记录来自不同次执行。tokens 使用 DSH 估算，不代表 API 计费。", continuationNote: "表内为“最终代码验收 / 成功摘要次数”。完整协议还要求 3 次摘要、3 次磁盘重载及最后阶段的续接。默认参数仍受统一 8,192-token 输出上限约束，测试采用手动边界。", noNative: "DeepSeek Harness 原生引擎未参与这些报告，不填入推测结果。", failureNote: "固定预算下：Qwen 为 37/43，其重试语义错误在首次压缩前已出现；ZCode 在第一阶段耗尽请求步数，未完成任务。失败记录完整保留。", readReport: "阅读全文", allPassed: "默认参数任务验收", protocolPassed: "默认参数完整协议", testCount: "最终验收项", phases: "开发阶段",
};

type Translation = { [K in keyof typeof zh]: typeof zh[K] extends string[] ? string[] : string };
const en: Translation = {
  diagramChecks: "43 acceptance checks", diagramRetention: "retention", diagramOld: "7 days", diagramNew: "48 hours", diagramDecision: "preserve the final decision",
  title: "Context strategy atlas", lab: "The laboratory", compare: "Compare mechanisms", cases: "Cases & evidence", github: "Source code", language: "切换到中文", skip: "Skip to main content",
  collection: "THE COLLECTION", count: "9 implementations", native: "NATIVE", adapters: "DSH ADAPTERS", edition: "FIELD NOTES / 01", sidebarNote: "One problem. Nine approaches.", sidebarDetail: "How coding agents remember the task, make room, and keep going.",
  eyebrow: "CONTEXT ENGINEERING", heading: "Every context decision, visible.", intro: "Follow a conversation as information is trimmed, condensed, retained, and restored.",
  viewSource: "Implementation notes", mechanism: "MECHANISM STUDY", simulation: "Illustrative data · no model calls", window: "Model window", scenario: "Conversation", scenarios: ["A long coding task", "Heavy tool output", "Changing requirements"],
  contextFlow: "The context flow", flowHint: "Select a step to inspect the change", before: "Original context", after: "The next request", original: "Full event log", originalHint: "Append-only · replayable", protected: "Instructions", conversation: "Dialogue", tools: "Tool results", recent: "Recent messages", summary: "Summary", restored: "Restored state", free: "Available space",
  play: "Play walkthrough", pause: "Pause", replay: "Play again", previous: "Previous step", next: "Next step", reset: "Reset", speed: "Playback speed", stage: "Step", waiting: "Awaiting checkpoint", retained: "Kept verbatim", condensed: "Condensed into summary", pruned: "Tool text trimmed", processing: "Preparing history", committed: "Checkpoint committed",
  tokensBefore: "Before", tokensAfter: "Projected", reduction: "Illustrative reduction", traceCaption: "This walkthrough follows one successful compaction path. Blocks and token counts are teaching examples; actual selection, summary size, and restoration depend on the session and configuration.",
  guard: "Original log retained", pairs: "Tool pairs intact", configured: "PATH NOTES", trigger: "Default trigger budget", threshold: "Trigger", retention: "Retention policy", recovery: "Recovery", formulaNote: "O = 8,192; no separate input limit. Trigger budgets follow implementation defaults. The flow is illustrative.",
  principle: "THE DESIGN DECISION", behavior: "Inside the pipeline", sourceNote: "SOURCE & ADAPTATION", explore: "Choose a strategy to explore a different approach to retention.", sourceDate: "SOURCE SNAPSHOT · 2026.10", footer: "Made to understand context.", project: "dsh-context-zoo / Context Atlas", allStrategies: "All strategies",
  compareEyebrow: "SIDE BY SIDE", compareHeading: "The same history. Different choices.", compareIntro: "Compare default budgets and recovery paths. Details follow the pinned sources and DSH adaptation notes.", strategy: "Implementation", pruning: "Tool pruning", defaultOn: "On by default", optional: "Optional", noPrune: "No separate stage", compareNote: "Native Harness and zoo adapters use different versions. Formulas share the same W and O assumptions; retention budgets have different meanings and should not be ranked directly.",
  casesEyebrow: "FROM THE WORKBENCH", casesHeading: "From a mechanism to a real task.", casesIntro: "Reproducible model observations, alongside context decisions in common engineering scenarios.", measured: "REPOSITORY EVIDENCE", illustrative: "ENGINEERING SCENARIO", caseOne: "One invoice. Ten stages of development.", caseOneDesc: "A real model builds an invoice importer, with compaction and disk reload after stages 3, 6, and 9, then continues to implement batch cancellation.", caseTwo: "When test logs fill the window.", caseTwoDesc: "Repeated stack traces and bulky tool output bury the useful details. Deciding what to trim comes before writing another summary.", caseThree: "A long task. Three changes of mind.", caseThreeDesc: "From the first proposal to the final constraints, preserve the user's actual decisions without reviving superseded requirements.", openCase: "Read case", closeCase: "Close case", exploreStrategy: "Explore in the lab", evidence: "Original report", context: "THE TASK", decision: "WHERE THE STRATEGY HELPS", outcome: "OBSERVATIONS & LIMITS",
  caseOneContext: "invoice-import-v2 covers idempotency, retries, tenant isolation, and batch cancellation. Each run starts a fresh project and session, ending with 43 acceptance checks.", caseOneDecision: "Eight adapters run with fixed and default budgets, sharing one uncompacted baseline: 17 runs in total. Three manual compaction boundaries are followed by disk reloads and continued coding.", caseOneOutcome: "With default parameters, 8/8 pass task acceptance, but only 5/8 pass the full protocol including three successful summaries. One run per mode cannot establish superiority. Native Harness was not evaluated.",
  caseTwoContext: "Illustration: a monorepo test failure creates repetitive logs. Keep failed assertions, relevant files, and the latest command useful without retaining all historical output in context.", caseTwoDecision: "Harness with a pruner can shorten tool results and remeasure before summarization. If pressure is relieved, it can skip the model call. Qwen and ZCode have different microcompaction triggers and protection rules.", caseTwoOutcome: "An engineering scenario derived from source behavior, not customer production data or a measured savings claim. Check each implementation's protection of errors, recent output, and tool-pair boundaries.",
  caseThreeContext: "Illustration: a migration plan changes retention from 7 days to 48 hours, adds tenant isolation, and forbids automatic production migrations. Earlier requirements must not override the final decision.", caseThreeDecision: "Codex retains recent user text; Kimi restores original user input after full summarization. Claude Code, Qwen, and ZCode also restore available plans and file state.", caseThreeOutcome: "Check that final constraints, pending tasks, and superseded plans remain distinct. The repository's single-compaction recall test uses synthetic facts; it does not replace validation on actual business data.",
  resultsTitle: "Real models. Original observations.", resultsIntro: "deepseek-flash · synthetic tasks · Sep 26 / 27 / 29, 2026", recall: "Compaction & recall", continuation: "Ten-stage continuation", beforeTokens: "Est. before", afterTokens: "Est. after", decrease: "Reduction", recallScore: "Fact recall", summaryCap: "Summary cap", fixed: "Fixed budget", defaults: "Default parameters", checks: "Code acceptance", compactions: "Summaries", incomplete: "Incomplete", notRank: "Single observations, not a leaderboard.", resultNote: "Recall uses the same 5,506-token synthetic history. Qwen has a 4,096-token summary cap; others use 2,048. Records span separate executions. DSH token estimates are not API billing tokens.", continuationNote: "Cells show final code acceptance / successful summaries. The full protocol also requires 3 summaries, 3 disk reloads, and final-stage continuation. Default parameters still share an 8,192-token output cap; boundaries are manual.", noNative: "Native DeepSeek Harness was not evaluated in these reports; no results are inferred.", failureNote: "Fixed budget: Qwen scores 37/43; its retry-semantics error appeared before the first compaction. ZCode exhausted its request budget in stage one and did not finish. Failure records are preserved.", readReport: "Read full report", allPassed: "Default task acceptance", protocolPassed: "Default full protocol", testCount: "Final acceptance checks", phases: "Development stages",
};
export const dictionaries = { zh, en };
// Window presets use binary multiples; model API limits may use other conventions.
export const formatWindow = (n: number) => n >= 1048576 ? `${n / 1048576}M` : `${n / 1024}K`;
export const formatTokens = (n: number) => n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(n);
export const number = (n: number) => n.toLocaleString("en-US");
export const localizedSource = (source: string, locale: Locale) => locale === "zh" && source.startsWith("https://github.com/zonemeen/") ? source.replace("README.md", "README.zh-CN.md") : source;
