/** Longer task: real feature changes accumulate between compaction boundaries. */
import { initialFiles, systemPrompt, phases as originalPhases, taskCases as originalCases, caseSource, editablePaths } from './continuation-task.mjs';

export { initialFiles, systemPrompt, caseSource, editablePaths };
export const taskId = 'invoice-import-v2';
export const compactAfter = [3, 6, 9];
export const phases = [
  ...originalPhases.map(phase => ({ ...phase, prompt: phase.prompt.replace(/of 4:/, 'of 10:') })),
  { id: 'selective-invalidation', prompt: `Stage 5 of 10: add store.remove({tenantId, key}). Remove exactly this tenant/key entry and return true if an entry was physically present, otherwise false. Do not remove another tenant's matching key. Entries may contain punctuation as before. Keep lookup/save behavior and all earlier policies. Run_tests after editing.` },
  { id: 'expired-entry-cleanup', prompt: `Stage 6 of 10: add store.prune(now) to remove all expired entries across tenants, returning the number physically removed by this call. Apply the latest retention and exact expiry boundary from earlier stages. Preserve live entries; repeating prune at the same time returns zero. Run_tests after editing.` },
  { id: 'forced-refresh', prompt: `Stage 7 of 10: add optional request.forceRefresh to importInvoice. When true, a matching cached fingerprint must be sent again using the agreed retry policy. A conflicting unexpired fingerprint must still return the documented conflict without sending. Successful refresh replaces the cached response and restarts retention from the save time. An unsuccessful response or transport exception must leave any still-valid old cached response available for an ordinary replay. Default behavior stays as previously agreed. Run_tests after editing.` },
  { id: 'batch-http-stop', prompt: `Stage 8 of 10: extend importBatch(requests, deps, options = {}) with options.stopOnHttpFailure. When true, append the first non-2xx response to the output and stop before processing the next item. The default behavior continues after HTTP failures as previously agreed. Thrown transport exceptions still propagate. Maintain sequential processing, response order, shared dependencies, and forceRefresh behavior. Run_tests after editing.` },
  { id: 'server-retry-delay', prompt: `Stage 9 of 10: extend retryDelay(status, attempt, retryAfterMs) and connect it to response.retryAfterMs in importInvoice. After confirming the response is retryable and another attempt is allowed, use retryAfterMs if it is a finite number in the inclusive range 0..60000; otherwise use the original delay schedule. Zero is valid. The hint must never make a permanent status retryable or permit an extra attempt. All earlier policies remain in force. Run_tests after editing.` },
  { id: 'batch-cancellation', prompt: `Stage 10 of 10: add optional options.signal to importBatch. Check signal.aborted before starting each item, including the first; if true, throw Error('Batch aborted') and do not send that item. An empty batch returns [] even with an aborted signal. This only cancels between items and does not interrupt an in-flight import. Preserve earlier batch options, replay, refresh, retry hints, tenant behavior and corrected retention. Run regression tests after the final edit and report observed results.` },
];

const additions = [
  ['remove-example', 5, false, `const s=store.createStore(); s.save({...identity,response}); eq(s.remove(identity),true); eq(s.lookup(identity),{kind:'miss'});`],
  ['remove-missing-and-repeat', 5, true, `const s=store.createStore(); eq(s.remove(identity),false); s.save({...identity,response}); eq(s.remove(identity),true); eq(s.remove(identity),false);`],
  ['remove-tenant-and-delimiter-isolation', 5, true, `const s=store.createStore(); const other={...identity,tenantId:'other'}; s.save({...identity,response}); s.save({...other,response}); eq(s.remove(identity),true); eq(s.lookup(other),{kind:'hit',response}); const a={...identity,tenantId:'a:b',key:'c'},b={...identity,tenantId:'a',key:'b:c'}; s.save({...a,response}); s.save({...b,response}); s.remove(a); eq(s.lookup(b),{kind:'hit',response});`],
  ['prune-example', 6, false, `const s=store.createStore(); s.save({...identity,response}); eq(s.prune(identity.now+policy.retentionMs),1); eq(s.lookup(identity),{kind:'miss'});`],
  ['prune-boundary-and-repeat', 6, true, `const s=store.createStore(); s.save({...identity,response}); eq(s.prune(identity.now+policy.retentionMs-1),0); eq(s.prune(identity.now+policy.retentionMs),1); eq(s.prune(identity.now+policy.retentionMs),0);`],
  ['prune-all-tenants-preserve-live', 6, true, `const s=store.createStore(); s.save({...identity,response}); s.save({...identity,tenantId:'b',response}); const live={...identity,tenantId:'c',now:identity.now+100}; s.save({...live,response}); eq(s.prune(identity.now+policy.retentionMs),2); eq(s.lookup({...live,now:identity.now+policy.retentionMs}),{kind:'hit',response});`],
  ['refresh-example', 7, false, `const second={status:201,body:'fresh'}; const f=fixture([response,second]); await importer.importInvoice(request,f.deps); eq(await importer.importInvoice({...request,forceRefresh:true},f.deps),second); eq(await importer.importInvoice(request,f.deps),second); eq(f.sent.length,2);`],
  ['refresh-conflict-still-blocked', 7, true, `const f=fixture([response]); await importer.importInvoice(request,f.deps); eq(await importer.importInvoice({...request,fingerprint:'changed',forceRefresh:true},f.deps),{status:409,body:{error:'idempotency_conflict'}}); eq(f.sent.length,1);`],
  ['refresh-failure-preserves-cache', 7, true, `for(const failed of [{status:400,body:'bad'},new Error('lost')]) { const f=fixture([response,failed]); await importer.importInvoice(request,f.deps); try { await importer.importInvoice({...request,forceRefresh:true},f.deps); } catch(e) { eq(e.message,'lost'); } eq(await importer.importInvoice(request,f.deps),response); eq(f.sent.length,2); }`],
  ['refresh-restarts-retention', 7, true, `const fresh={status:201,body:'fresh'}; const f=fixture([response,fresh]); await importer.importInvoice(request,f.deps); f.time+=40*60*60*1000; await importer.importInvoice({...request,forceRefresh:true},f.deps); f.time+=10*60*60*1000; eq(await importer.importInvoice(request,f.deps),fresh); eq(f.sent.length,2);`],
  ['batch-stop-example', 8, false, `const bad={status:400,body:'bad'}; const f=fixture([bad,response]); eq(await importer.importBatch([request,{...request,key:'second'}],f.deps,{stopOnHttpFailure:true}),[bad]); eq(f.sent.length,1);`],
  ['batch-stop-includes-later-failure', 8, true, `const bad={status:500,body:'bad'}; const f=fixture([response,bad,response]); eq(await importer.importBatch([request,{...request,key:'b'},{...request,key:'c'}],f.deps,{stopOnHttpFailure:true}),[response,bad]); eq(f.sent.length,2);`],
  ['batch-stop-conflict', 8, true, `const f=fixture([response]); await importer.importInvoice(request,f.deps); eq(await importer.importBatch([{...request,fingerprint:'other'},{...request,key:'b'}],f.deps,{stopOnHttpFailure:true}),[{status:409,body:{error:'idempotency_conflict'}}]); eq(f.sent.length,1);`],
  ['retry-hint-example', 9, false, `eq(policy.retryDelay(503,1,700),700);`],
  ['retry-hint-bounds-and-fallback', 9, true, `for(const hint of [0,60000]) eq(policy.retryDelay(503,1,hint),hint); for(const hint of [-1,60001,NaN,Infinity,'100',null]) { eq(policy.retryDelay(503,1,hint),250); eq(policy.retryDelay(503,2,hint),500); } eq(policy.retryDelay(500,1,100),null); eq(policy.retryDelay(503,3,100),null);`],
  ['retry-hint-import-integration', 9, true, `const f=fixture([{status:503,body:'busy',retryAfterMs:0},{status:429,body:'busy',retryAfterMs:900},response]); eq(await importer.importInvoice(request,f.deps),response); eq(f.waits,[0,900]); eq(f.sent.length,3);`],
  ['batch-cancel-example', 10, false, `const f=fixture([response]); let caught=false; try { await importer.importBatch([request],f.deps,{signal:{aborted:true}}); } catch(e) { caught=e.message==='Batch aborted'; } eq(caught,true); eq(f.sent.length,0);`],
  ['batch-cancel-between-items', 10, true, `const f=fixture([]); const signal={aborted:false}; f.deps.send=async input=>{ f.sent.push(input); signal.aborted=true; return response; }; let caught=false; try { await importer.importBatch([request,{...request,key:'b'}],f.deps,{signal}); } catch(e) { caught=e.message==='Batch aborted'; } eq(caught,true); eq(f.sent.length,1);`],
  ['batch-cancel-empty', 10, true, `const f=fixture([]); eq(await importer.importBatch([],f.deps,{signal:{aborted:true}}),[]);`],
];

export function taskCases(phase, acceptance = false) {
  if (!Number.isInteger(phase) || phase < 1 || phase > phases.length) throw new Error('Invalid task phase.');
  return [...originalCases(Math.min(phase, 4), acceptance), ...additions.filter(([,start,hidden]) => start <= phase && (acceptance || !hidden)).map(([name,,,body]) => ({name,body}))];
}
