"use client";

import { useState } from "react";
import { BookOpen, Check, ChevronDown, ChevronUp, CircleHelp, FileCode2, FlaskConical, GitBranch, Layers3, Terminal, X } from "lucide-react";
import { dictionaries, number } from "@/lib/i18n";
import { observations, REPO, reportUrl, strategies, type Locale, type StrategyId } from "@/lib/strategies";

export function Cases({ locale, onExplore }: { locale: Locale; onExplore: (id: StrategyId) => void }) {
  const [openCase, setOpenCase] = useState<number | null>(null);
  const [report, setReport] = useState<"recall" | "continuation">("continuation");
  const t = dictionaries[locale];
  const cases = [
    { title: t.caseOne, description: t.caseOneDesc, category: t.measured, icon: FileCode2, context: t.caseOneContext, decision: t.caseOneDecision, outcome: t.caseOneOutcome, id: "pi" as const },
    { title: t.caseTwo, description: t.caseTwoDesc, category: t.illustrative, icon: Terminal, context: t.caseTwoContext, decision: t.caseTwoDecision, outcome: t.caseTwoOutcome, id: "deepseek" as const },
    { title: t.caseThree, description: t.caseThreeDesc, category: t.illustrative, icon: GitBranch, context: t.caseThreeContext, decision: t.caseThreeDecision, outcome: t.caseThreeOutcome, id: "kimi-code" as const },
  ];
  return <>
    <div className="page-intro"><div><p className="eyebrow"><span />{t.casesEyebrow}</p><h1>{t.casesHeading}</h1><p className="intro-description">{t.casesIntro}</p></div></div>
    <div className="case-grid">{cases.map((item, index) => <article className={`case-card ${index === openCase ? "case-open" : ""}`} key={item.id}>
      <div className="case-meta"><span className={`case-category ${index === 0 ? "measured" : ""}`}>{item.category}</span><span>0{index + 1}</span></div>
      <div className={`case-diagram case-diagram-${index}`} aria-hidden="true">{index === 0 ? <><div className="case-stage-line">{Array.from({ length: 10 }, (_, i) => <span className={[2, 5, 8].includes(i) ? "checkpoint-stage" : ""} key={i}>{String(i + 1).padStart(2, "0")}</span>)}</div><div className="case-checkpoints"><span>compact</span><span>compact</span><span>compact</span></div><div className="mini-checks"><Check size={12} /><span>{t.diagramChecks}</span></div></> : index === 1 ? <><div className="terminal-demo"><div><span>$</span> pnpm test <i>···</i></div><div className="terminal-lines"><span /><span /><span /><span /><span /><span /></div></div><span className="terminal-divider"><Layers3 size={19} /></span><div className="terminal-clean"><span /><span /><span /><Check size={15} /></div></> : <><div className="requirements-note old"><span>{t.diagramRetention}</span><s>{t.diagramOld}</s></div><div className="requirements-line" /><div className="requirements-note new"><span>{t.diagramRetention}</span><strong>{t.diagramNew}</strong><Check size={13} /></div><div className="requirement-caption">{t.diagramDecision}</div></>}</div>
      <h2>{item.title}</h2><p>{item.description}</p><button className="case-open-button" onClick={() => setOpenCase(current => current === index ? null : index)} aria-expanded={openCase === index} aria-controls={`case-detail-${index}`}>{openCase === index ? t.closeCase : t.openCase}{openCase === index ? <ChevronUp size={14} /> : <ChevronDown size={14} />}</button>
    </article>)}</div>
    {openCase !== null && <section className="case-detail" id={`case-detail-${openCase}`} aria-label={cases[openCase].title}><div className="case-detail-header"><div><span>0{openCase + 1}</span><h2>{cases[openCase].title}</h2></div><button aria-label={t.closeCase} onClick={() => setOpenCase(null)}><X size={18} /></button></div><div className="case-detail-body">{[{ title: t.context, text: cases[openCase].context }, { title: t.decision, text: cases[openCase].decision }, { title: t.outcome, text: cases[openCase].outcome }].map(item => <div key={item.title}><h3>{item.title}</h3><p>{item.text}</p></div>)}</div><div className="case-detail-actions"><button className="secondary-button" onClick={() => onExplore(cases[openCase].id)}><FlaskConical size={14} />{t.exploreStrategy}</button>{openCase === 0 && <a href={reportUrl(locale)} className="text-link" target="_blank" rel="noreferrer"><BookOpen size={14} />{t.evidence}</a>}</div></section>}
    <section className="evidence-section" aria-label={t.resultsTitle}>
      <div className="evidence-heading"><div><p className="eyebrow muted"><FlaskConical size={14} />{t.measured}</p><h2>{t.resultsTitle}</h2><p>{t.resultsIntro}</p></div><a href={report === "continuation" ? reportUrl(locale) : `${REPO}/blob/main/reports/deepseek/2026-09-26/README${locale === "zh" ? ".zh-CN" : ""}.md`} className="text-link" target="_blank" rel="noreferrer"><BookOpen size={14} />{t.readReport}</a></div>
      <div className="evidence-stats"><div><strong>10</strong><span>{t.phases}</span></div><div><strong>43</strong><span>{t.testCount}</span></div><div><strong>8<span>/8</span></strong><span>{t.allPassed}</span></div><div><strong>5<span>/8</span></strong><span>{t.protocolPassed}</span></div></div>
      <div className="report-controls"><div className="report-switch" role="group" aria-label={t.resultsTitle}><button className={report === "continuation" ? "active" : ""} aria-pressed={report === "continuation"} onClick={() => setReport("continuation")}>{t.continuation}</button><button className={report === "recall" ? "active" : ""} aria-pressed={report === "recall"} onClick={() => setReport("recall")}>{t.recall}</button></div><span>{t.notRank}</span></div>
      <div className="results-table-wrap"><table className="results-table"><thead><tr><th>{t.strategy}</th>{report === "continuation" ? <><th>{t.fixed}<small>{t.checks} / {t.compactions}</small></th><th>{t.defaults}<small>{t.checks} / {t.compactions}</small></th><th>{t.compactions}<small>{t.defaults}</small></th></> : <><th>{t.beforeTokens}</th><th>{t.afterTokens}</th><th>{t.decrease}</th><th>{t.recallScore}</th><th>{t.summaryCap}</th></>}</tr></thead><tbody>{observations.map(row => { const strategy = strategies.find(s => s.id === row.id)!; return <tr key={row.id}><th><button onClick={() => onExplore(strategy.id)}><span className="strategy-mark" style={{ color: strategy.color }}>{strategy.mark}</span>{strategy.name}</button></th>{report === "continuation" ? <><td><span className={!row.fixed || row.fixed !== "43/43" ? "result-warning" : ""}>{row.fixed ?? t.incomplete}</span><span className="result-divider"> / </span><span className="summary-count">{row.fixedCompactions}</span></td><td>43/43<span className="result-divider"> / </span><span className="summary-count">{row.nativeCompactions}</span></td><td><div className="summary-dots" aria-label={`${row.nativeCompactions} / 3`}>{[1, 2, 3].map(i => <span key={i} className={row.nativeCompactions >= i ? "filled" : ""}>{row.nativeCompactions >= i && <Check size={10} />}</span>)}</div></td></> : <><td className="muted-cell">5,506</td><td>{number(row.after)}</td><td><span className="reduction-mini"><i style={{ width: `${row.reduction}%` }} /></span>{row.reduction}%</td><td>10/10</td><td className="muted-cell">{number(row.cap)}</td></>}</tr>; })}</tbody></table></div>
      <div className="evidence-notes"><p><CircleHelp size={14} />{report === "continuation" ? t.continuationNote : t.resultNote}</p>{report === "continuation" && <p>{t.failureNote}</p>}<p>{t.noNative}</p><div className="report-source-links">{report === "recall" ? <><a href={`${REPO}/blob/main/reports/deepseek/2026-09-26/README${locale === "zh" ? ".zh-CN" : ""}.md`} target="_blank" rel="noreferrer">2026-09-26 · {t.readReport}</a><a href={`${REPO}/blob/main/reports/deepseek/2026-09-27/README${locale === "zh" ? ".zh-CN" : ""}.md`} target="_blank" rel="noreferrer">2026-09-27 · Cline</a></> : <a href={reportUrl(locale)} target="_blank" rel="noreferrer">2026-09-29 · invoice-import-v2</a>}</div></div>
    </section>
  </>;
}
